version: "3.8"

services:
  app:
    container_name: authflow-store
    image: authflow-store-image
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      database:
          condition: service_healthy
    networks:
      - authflow-store_net
    ports:
      - 8000:8000
  database:
    container_name: authflow-store-db
    image: postgres
    restart: always
    hostname: db
    networks:
      - authflow-store_net
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
            test: "exit 0"

volumes:
  db-data:

networks:
  authflow-store_net:
    driver: bridge