version: "3.8"

services:
  app:
    container_name: authflow-store
    image: authflow-store-image
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      database:
          condition: service_healthy
      redis:
          condition: service_healthy
    networks:
      - authflow-store_net
    ports:
      - 8000:8000
  database:
    container_name: authflow-store-db
    image: postgres
    restart: always
    hostname: db
    networks:
      - authflow-store_net
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
            test: "exit 0"
  redis:
        image: "redis:alpine"
        container_name: authflow-store_redis
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf
        # environment:
        #     - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379
        networks:
          - authflow-store_net
        # command: redis-server --requirepass MDNcVb924a --loglevel warning
        command: redis-server
        healthcheck:
            test: "exit 0"

volumes:
  db-data:
  redis-data:
  redis-conf:

networks:
  authflow-store_net:
    driver: bridge